version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /src
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: new_root_password
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql

volumes:
  mysql:
  vendor_bundle:
  node_modules:
  storage:
